<?php

namespace ContainerITtNyms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZVDpzwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZV_dpzw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZV_dpzw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CreateController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DetailBookController::index' => ['privates', '.service_locator.sHr6cJT', 'get_ServiceLocator_SHr6cJTService', true],
            'App\\Controller\\EditorController::delete' => ['privates', '.service_locator.JIqO6E6', 'get_ServiceLocator_JIqO6E6Service', true],
            'App\\Controller\\EditorController::edit' => ['privates', '.service_locator.JIqO6E6', 'get_ServiceLocator_JIqO6E6Service', true],
            'App\\Controller\\EditorController::index' => ['privates', '.service_locator.2U04VOX', 'get_ServiceLocator_2U04VOXService', true],
            'App\\Controller\\EditorController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EditorController::show' => ['privates', '.service_locator.svhLOMM', 'get_ServiceLocator_SvhLOMMService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CreateController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DetailBookController:index' => ['privates', '.service_locator.sHr6cJT', 'get_ServiceLocator_SHr6cJTService', true],
            'App\\Controller\\EditorController:delete' => ['privates', '.service_locator.JIqO6E6', 'get_ServiceLocator_JIqO6E6Service', true],
            'App\\Controller\\EditorController:edit' => ['privates', '.service_locator.JIqO6E6', 'get_ServiceLocator_JIqO6E6Service', true],
            'App\\Controller\\EditorController:index' => ['privates', '.service_locator.2U04VOX', 'get_ServiceLocator_2U04VOXService', true],
            'App\\Controller\\EditorController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EditorController:show' => ['privates', '.service_locator.svhLOMM', 'get_ServiceLocator_SvhLOMMService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CreateController::index' => '?',
            'App\\Controller\\DetailBookController::index' => '?',
            'App\\Controller\\EditorController::delete' => '?',
            'App\\Controller\\EditorController::edit' => '?',
            'App\\Controller\\EditorController::index' => '?',
            'App\\Controller\\EditorController::new' => '?',
            'App\\Controller\\EditorController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CreateController:index' => '?',
            'App\\Controller\\DetailBookController:index' => '?',
            'App\\Controller\\EditorController:delete' => '?',
            'App\\Controller\\EditorController:edit' => '?',
            'App\\Controller\\EditorController:index' => '?',
            'App\\Controller\\EditorController:new' => '?',
            'App\\Controller\\EditorController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
