<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItI19vU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItI19vU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItI19vU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItI19vU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItI19vU\App_KernelDevDebugContainer([
    'container.build_hash' => 'ItI19vU',
    'container.build_id' => 'e3d29cba',
    'container.build_time' => 1708520428,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItI19vU');
