<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsdIxxg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsdIxxg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWsdIxxg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWsdIxxg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWsdIxxg\App_KernelDevDebugContainer([
    'container.build_hash' => 'WsdIxxg',
    'container.build_id' => 'a621f1d2',
    'container.build_time' => 1708597158,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsdIxxg');
