<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZB7RpEm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZB7RpEm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZB7RpEm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZB7RpEm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZB7RpEm\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZB7RpEm',
    'container.build_id' => 'cd26cc1e',
    'container.build_time' => 1708528280,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZB7RpEm');
