<?php

namespace ContainerZB7RpEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditor2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.svhLOMM.App\Entity\Editor' shared service.
     *
     * @return \App\Entity\Editor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.svhLOMM": it needs an instance of "App\\Entity\\Editor" but this type has been excluded in "config/services.yaml".');
    }
}
