<?php

namespace ContainerFH1K9Fo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SvhLOMMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.svhLOMM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.svhLOMM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'editor' => ['privates', '.errored..service_locator.svhLOMM.App\\Entity\\Editor', NULL, 'Cannot autowire service ".service_locator.svhLOMM": it needs an instance of "App\\Entity\\Editor" but this type has been excluded in "config/services.yaml".'],
        ], [
            'editor' => 'App\\Entity\\Editor',
        ]);
    }
}
